### ISSUE TITLE
Small typo in sample code in Readme.md

### ISSUE THREAD

**Issue by quinagh** [launchdarkly/xamarin-client#4]
Unexpected variable **username**.

```
 User user = User.WithKey(username);
 LdClient ldClient = LdClient.Init("YOUR_MOBILE_KEY", **username**);
```

should read

```
 User user = User.WithKey(username);
 LdClient ldClient = LdClient.Init("YOUR_MOBILE_KEY", **user**);
```

User is located in LaunchDarkly.Common so the Usings should be

```
using LaunchDarkly.Common;
using LaunchDarkly.Xamarin;
```

**Comment by eli-darkly** [comment]
Thanks, I'll fix the user/username thing.

However, this is incorrect:
> using LaunchDarkly.Common;

The User class is in the LaunchDarkly.Common _assembly_, but that doesn't mean that is its namespace. Its namespace is `LaunchDarkly.Client`, so that's what you have to put for `using`.

The reason for this is historical: we wrote the server-side .NET client first, and named both the assembly and the namespace `LaunchDarkly.Client`. When we later developed the Xamarin client, it was clear that some of the API code, including classes like `User`, would be the same in both clients, so we moved that code into a new assembly `LaunchDarkly.Common` so it could be maintained in just one place. However, we could not change the namespace of those classes without breaking existing code that uses the .NET client.

**Comment by quinagh** [comment]
Yeah, the Common/Client was a typo on my part :)
